import Head from "next/head";
import { Box, Button, Toolbar, Typography } from "@mui/material";
import { useRouter } from "next/router";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";

import React from "react";
import toast, { Toaster } from "react-hot-toast";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Link from "next/link";
import Navbar from "../components/navbar";

export default function Home() {
  const router = useRouter();
  const session = useSession();
  const supabase = useSupabaseClient();


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>

      
      <main>
      <Toolbar/>
      <> Landing page </>
      </main>
    </>
  );
}
