import Head from "next/head";
import { Toolbar } from "@mui/material";

import React from "react";
import Navbar from "../components/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Toolbar />
        <img src="https://images.hdqwalls.com/download/marvel-vs-dc-1u-1920x1080.jpg" alt="landing page" style={{
              maxWidth: "100%",
              overflow: "hidden",
              objectFit: "cover",
              width: "100%",
              backgroundRepeat: "no-repeat",
              backgroundAttachment: "fixed"
        }}/>
      </main>
    </>
  );
}
